apiVersion: v1
kind: Namespace
metadata:
  name: spicaengine
---
apiVersion: v1
kind: Pod
metadata:
  name: spica
  namespace: spicaengine
  labels:
    app: spica
spec:
  containers:
    - name: site
      image: spicaengine/site
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spica-svc
  namespace: spicaengine
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: spica
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spica-gateway
  namespace: spicaengine
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - spicaengine.com
      secretName: spicaengine-cert
  rules:
    - host: spicaengine.com
      http:
        paths:
          - backend:
              serviceName: spica-svc
              servicePort: 80
